name: Deploy to S3
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: santhoshn16/my-gpt-frontend
          ref: main
      - name: Install dependencies
        run: npm install
      - name: Build the app
        run: npm run build
      - name: Deploy to S3
        env:
          AWS_REGION: us-east-2
        run: |
          aws configure set aws_access_key_id ${{ secrets.ACCESS_ID_KEY }}
          aws configure set aws_secret_access_key ${{ secrets.ACCESS_KEY }}
          aws s3 sync build/ s3://my-gpt-bucket
